// App Action Types - Following existing project pattern
export const APP_TYPE = {
    // App Actions
    ON_APP_INITIALIZE: 'ON_APP_INITIALIZE',
    INCREMENT_APP_OPEN_COUNTER: 'INCREMENT_APP_OPEN_COUNTER',
    SET_APP_LANGUAGE: 'SET_APP_LANGUAGE',
    SET_USER_LOCATION: 'SET_USER_LOCATION',
    SET_LATEST_APP_VERSION: 'SET_LATEST_APP_VERSION',
    SET_LOCATION_ASKED: 'SET_LOCATION_ASKED',
    CHANGE_LOCATION_ACTION: 'CHANGE_LOCATION_ACTION',

    // View Actions
    RESET_SELECTED_DATE: 'RESET_SELECTED_DATE',
    SET_SELECTED_DATE: 'SET_SELECTED_DATE',
    SET_FETCHING_LOCATION: 'SET_FETCHING_LOCATION',
    SET_CURRENT_PLAYING_AUDIO: 'SET_CURRENT_PLAYING_AUDIO',

    // Saga Actions
    REFRESH_USER_CURRENT_LOCATION: 'REFRESH_USER_CURRENT_LOCATION',
    PLAY_AUDIO_TRACK: 'PLAY_AUDIO_TRACK',
    STOP_AUDIO_TRACK: 'STOP_AUDIO_TRACK',
    PERFORM_APP_DEVELOPER_ACTION: 'PERFORM_APP_DEVELOPER_ACTION'
} as const;
