// View Action Types - Following existing project pattern
export const VIEW_TYPE = {
    // View Actions
    RESET_SELECTED_DATE: 'RESET_SELECTED_DATE',
    SET_SELECTED_DATE: 'SET_SELECTED_DATE',
    SET_FETCHING_LOCATION: 'SET_FETCHING_LOCATION',
    SET_CURRENT_PLAYING_AUDIO: 'SET_CURRENT_PLAYING_AUDIO',

    // Saga Actions
    PLAY_AUDIO_TRACK: 'PLAY_AUDIO_TRACK',
    STOP_AUDIO_TRACK: 'STOP_AUDIO_TRACK'
} as const;
